version: '3'
services:
  api:
    build: ./
    depends_on:
      - database
    environment:
      NODE_ENV: development
      APP_PORT: 3000
    ports:
      - "3000:3000"
    networks:
      - typeorm
  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: login_node
      MYSQL_USER: styde
      MYSQL_PASSWORD: secret
    ports:
      - 3306:3306
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - typeorm
networks:
  typeorm:
    driver: "bridge"
volumes:
  mysqldata:
    driver: "local"
