version: '3.8'
services:
  database:
    image: mysql:5.6
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
  api:
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - database
    environment:
      NODE_ENV: development
      PORT: 3000
    ports:
      - "3000:3000"
